<?php

/**
 * @file
 * Contains fitbit.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fitbit_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fitbit module.
    case 'help.page.fitbit':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Fitbit API wrapper module for connecting to Fitbit.') . '</p>';
      return $output;

    default:
  }
}
