<?php

/**
 * @file
 *  Module file for fitbit user integration.
 */

/**
 * Implements hook_menu().
 */
function fitbit_user_menu() {
  $items = array();
  $items['fitbit/auth/%user'] = array(
    'title' => 'Fitbit User Authorization Callback',
    'page callback' => 'fitbit_user_auth_callback',
    'page arguments' => array(2),
    'access callback' => 'fitbit_user_auth_callback_access',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function fitbit_user_permission() {
  return array(
    'authorize fitbit account' => array(
      'title' => t('Authorize Fitbit Account'),
      'description' => t('Authorize the site to access this user\'s personal Firbit account.'),
    ),
    'administer fitbit users' => array(
      'title' => t('Administer Fitbit Users'),
      'description' => t('Administer fitbit authorizations on users.'),
    ),
  );
}

/**
 * Implements hook_user_view().
 */
function fitbit_user_user_view($account) {
  global $user;
  // Show fitbit authorization info.
  if ((user_access('authorize fitbit account') && $user->uid == $account->uid)
      || user_access('administer fitbit users')) {

    // Message depends on whether the user has a connected account or not.
    if (!empty($account->fitbit_tokens['fitbit_uid'])) {
      $message = t('This user is paired with the fibit account %id.', array('%id' => $account->fitbit_tokens['fitbit_uid']));
    }
    else {
      $message = t('This user is not paired with an authorized Fitbit account.  Go !here to authorize.', array('!here' => l(t('here'), "fitbit/auth/{$account->uid}")));
    }

    $account->content['fitbit_info'] = array(
      '#type' => 'item',
      '#title' => t('Fitbit'),
      '#markup' => $message,
      '#weight' => 5,
    );
  }
}

/**
 * Fitbit authorization page.
 *
 * This redirects to Fitbit for authorization
 * and then gets the access keys.
 *
 * @param object $account
 *  A loaded Drupal user account.
 */
function fitbit_user_auth_callback($account) {
  global $base_url;
  $client = fitbit_get_client();
  // Redirect to fitbit in order for user to allow authentication.
  if (empty($_GET['oauth_token'])) {
    $request_token_info = $client->oauth->getRequestToken($client->getParam('requestTokenUrl'), $base_url . '/fitbit/auth/' . $account->uid);
    $_SESSION['fitbit_request_token'] = $request_token_info;
    header('Location: ' . $client->getParam('authUrl') . '?oauth_token=' . $request_token_info['oauth_token']);
    // We return here, because this will send a user
    // over to the auth page at fitbit.com.
    return;
  }

  // Once fitbit has sent us back here, we get some access tokens for continued use.
  $request_token = $_GET['oauth_token'];
  $client->oauth->setToken($request_token, $_SESSION['fitbit_request_token']['oauth_token_secret']);
  $access_token_info = $client->oauth->getAccessToken($client->getParam('accessTokenUrl'));
  unset($_SESSION['fitbit_request_token']);
  module_invoke_all('fitbit_user_post_authenticate', $account, $access_token_info);
  drupal_set_message('Sucessfully authenticated with Fitbit');
  drupal_goto('user/' . $account->uid);
}

/**
 * Determine if this user should have access to authorize this site to access their Fitbit account.
 */
function fitbit_user_auth_callback_access() {
  return user_access('authorize fitbit account') && !user_is_anonymous();
}

/**
 * Implements hook_fitbit_user_authenticate().
 */
function fitbit_user_fitbit_user_post_authenticate($account, $access_token_info) {
  fitbit_user_update_authentication_info($account, $access_token_info);
}

/**
 * Implements hook_user_delete().
 */
function fitbit_user_user_delete($account) {
  fitbit_user_delete_tokens($account);
}

/**
 * Implements hook_user_load().
 */
function fitbit_user_user_load($accounts) {
  foreach ($accounts as $account) {
    fitbit_user_get_tokens($account);
  }
}

/**
 * Update/Add a user's fitbit access credentials.
 *
 * @param object $account
 *  A loaded drupal user object with uid.
 * @param array $access_token_info
 *  The data received from getting the oauth access token for a user.
 *   - encoded_user_id, oauth_token, oauth_token_secret
 *
 * @return int
 *  The merge query status.
 */
function fitbit_user_update_authentication_info($account, $access_token_info) {
  $account->fitbit_tokens = array(
    'uid' => $account->uid,
    'fitbit_uid' => $access_token_info['encoded_user_id'],
    'access_token' => $access_token_info['oauth_token'],
    'access_secret' => $access_token_info['oauth_token_secret'],
  );
  return db_merge('fitbit_user_tokens')
  ->key(array('uid' => $account->uid))
  ->fields($account->fitbit_tokens)
  ->execute();
}

/**
 * Delete an entry from the access tokens table.
 *
 * @param object $account
 *  A valid loaded druapl user object.
 *
 * @return int
 *  Number of rows deleted (Should be 0 or 1).
 */
function fitbit_user_delete_tokens($account) {
  return db_delete('fitbit_user_tokens')
  ->condition('uid', $account->uid)
  ->execute();
}

/**
 * Load oauth access tokens with the account.
 *
 * @param object $account
 *  A valid loaded druapl user object.
 *
 * @return void
 */
function fitbit_user_get_tokens($account) {
  $account->fitbit_tokens = db_select('fitbit_user_tokens', 'f')
  ->fields('f')
  ->condition('uid', $account->uid)
  ->execute()
  ->fetchAssoc();
}

/**
 * Load a user from their fitbit user id.
 *
 * @param string $fitbit_uid
 *  A user's fitbit user id.
 * @param boolean $reset
 *  Whether or not to reload from the database.
 *
 * @return object|NULL
 */
function fitbit_user_load_account_by_fitbit_id($fitbit_uid, $reset = FALSE) {
  $account = NULL;
  $accounts = &drupal_static(__FUNCTION__, array());
  if (empty($accounts[$fitbit_uid]) || $reset) {
    $accounts[$fitbit_uid] = db_select('fitbit_user_tokens', 'f')
      ->fields('f', array('uid'))
      ->condition('fitbit_uid', $fitbit_uid)
      ->execute()
      ->fetchCol();
  }
  if (!empty($accounts[$fitbit_uid])) {
    $account = user_load($accounts[$fitbit_uid], $reset);
  }
  return $account;
}

/**
 * Add a subscription to a user.
 *
 * @param string $collection
 *  The type of collection for the subscription (activity, food, body...)
 * @param string $subscription_id
 *  The id of the existing subscription in your fitbit app.
 * @param object $account
 *  Loaded Drupal user account.
 *
 * @return
 */
function fitbit_user_add_subscription($collection, $subscription_id, $account) {
  return fitbit_add_subscription($collection, $subscription_id, $account->fitbit_tokens['access_token'], $account->fitbit_tokens['access_secret']);
}
